[project]
name = "pokemlops"
version = "0.1.0"
description = "A simple ML binary classification app predicting pokemon status"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    'pandas',
    'scikit-learn',
    'vetiver',
    'pathlib',
    'pins',
    'polars',
    'pyarrow',
]
